
on:
  push:
    branches: [staging]

name: Staging Deploy to Amazon ECS

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, lint, and test
        run: |
          npm ci
          # npm run lint
          npm audit
          # npm test
        env:
          CI: true
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t "$IMAGE_TAG" .


